spring.application.name=srm-credit-engine

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/srm_credit_engine
spring.datasource.username=srm
spring.datasource.password=srm
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC